"""empty message

Revision ID: 88c933cba6ff
Revises: None
Create Date: 2016-03-23 19:51:09.472775

"""

# revision identifiers, used by Alembic.
revision = '88c933cba6ff'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('myprofile', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('myprofile', 'first_name',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.create_unique_constraint(None, 'myprofile', ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'myprofile', type_='unique')
    op.alter_column('myprofile', 'first_name',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.drop_column('myprofile', 'id')
    ### end Alembic commands ###
